language: node_js
node_js: '10'
cache:
  directories:
  - "~/.npm"
  - "~/.cache"
branches:
  only:
  - master
stages:
- test
install:
- yarn --ignore-engines
- npm install -g typescript
script:
- yarn test 
notifications:
  email:
    on_success: change
    on_failure: change
services:
- mongodb