language: node_js
node_js: '10'
cache:
  directories:
  - "~/.npm"
  - "~/.cache"
branches:
  only:
  - master
stages:
- test
install:
- yarn --ignore-engines
- npm install -g typescript
script:
- npm run coverage:prep && nyc --reporter=lcov npm run cypress
after_success:
- cat coverage/lcov.info | coveralls
notifications:
  email:
    on_success: change
    on_failure: change