language: node_js
node_js: '10'
cache:
  directories:
  - "~/.npm"
  - "~/.cache"
branches:
  only:
  - master
stages:
- test

install:
- yarn --ignore-engines
- npm install -g typescript
- npm install -g codecov
script:
- yarn "coverage:$TEST"
- yarn compile:examples
- gulp prepareWebsite
after_script:
- codecov -f coverage/lcov.info -F $(echo "$TEST" | sed  's/[\._-]//g')

deploy:
  provider: npm
  email: awsdfgvhbjn@gmail.com
  api_key:
    secure: dAMHGYv/2jJ8DBj6AMVeJBe7LAzXBF1PV649K4ArAZs93pQuDyMPU/8tVeteYOrUv344MkPo8oszS0d9ovG5EMVuspYgskozZjxd+LDlQQs76V03LscWZyHdPgRyVnyZ3wCKqrd5gNCdT72XeJ9HpNkIVUrIhiLGpg10YYCzMR5KqAzMrRKXzmCg8lSSpqTn58CuWgfQVt7cYvNBYRSIQ78+Wp6ItcfZC20gnFoAAQ+hTBTH7CA/LPjkk6UWYmeqmMiKfIJpwWL9pRKPiwtTZWPToQbL/d9Xs2Kw+9XaJ3VPnWpbLOxxm6t0UkQf4bkctBYji0zewgYsSh/tiUTz+q6A7NK0WrlIwpmn6H1zRb0nbsJj9hJEu/M2t3h5/5ABvptNgFF9aMe2hsnspp+742Muss9q0H5fXztprIvaj+dzlIJRCouN5t/MRD3qyceBcofqSHdr12L34zIq+oE8h/jxHab0X6pmT88vKmw0UIzdDpdcKZTdy8KQfCjEUmNlBfSVB4AmAS+qRJ/ALyuHNDXuFRGS1Ne8mrVu2QH8NPnvqzVDJGP7zNbR1t6RMW512yp2NUyR9mP3EXbUcjYexkRWIZYh1wHH+EQfnVhl4ZwV4IVIQP7cB0Koc5qmDWrpWIPW3EUb+A/ta3JfUfjtsDFN9RPJuJR/KiuWI6mmJQQ=
  on:
    tags: true
    branch: master
notifications:
  email:
    on_success: change
    on_failure: change
env:
  matrix:
  - TEST=classes
  - TEST=lib
  - TEST=properties
  - TEST=partial-classes-basic
  - TEST=partial-classes-complex-template
  - TEST=partial-classes-i18n
  - TEST=partial-classes-theming
  - TEST=tasks
  global:
  - secure: gk0qwWSGXiPnRo5V7C7xeim+ieuqBCXyA+6Lt0bbLgE9bI9XbBMz3UHvXL/25A+WqpWnM9WQGSUqpz8wGOSTGpLEYYpjr41CTJZeO64iwH0wbhdE8BGxB53Er4pkIQJ55CeUB5hIeWGzHWWT6SU1GNnw1MedhGKF0JfA2APP6a6GV+6skl2Bo+bba1F0jCmICHVahd6NgVGm5c6Pk0Ql/tcPZln5FGNGWmvtm4/l6MT9WEWrV+Xe4/Aegpx8EoF5h5s1ENzSDo9sOQoI1htVJ1Zbdg9R7ysd/UJKPrJUI0G/a1DbDSVdUhw+TrYl6v77R/brV93Llr56zHBtUk02/SNNG69LGnAJHZKbP2xUKqUOQmdU8wi0kCisw5HdWyNvK2I+D6ajiv12GGaMwYEOYuL/OXQ+0cTUSpE8MNIvwQxATVPP24VwK03FQpSeFlO+HN1tr7Qqbn/eIPHiBEW3x0SzaayEH2NAxPV+t1LcHc53POWvDPqSRcDUCllcUiJXb+35uoZb3256e0f2evCZxpgTY91VAPEwr9I3vpkEQSMBSQASuNTZPaPf4Fh7Nkwf04E6Ch5yTOSfS0xJr8hMcBknKLG5J2b7AHqlS1uu6cDhkyjf6Crp/WFNhmXjiKyQEyp3Z9f30eqz6fvIIlNpXyTqGQnwQXcLoXH/b9BHfR4=
addons:
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
    - libgconf-2-4