name: "Deploy examples website"

on:
  push:
    branches:
      - master
    tags:
      - "*.*.*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          yarn --ignore-engines
          yarn global add typescript makfy
          makfy compile --dir examples
          makfy website

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.2
        with:
          branch: gh-pages
          folder: examples
          dry-run: true
